---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'EC2 Postgres and EC2 Redis deployments for Yelb backends'
  Parameters:
    KeyName:
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
        (where applicable)
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: Can contain only ASCII characters.
    InstanceType:
      Description: Yelb EC2 instance type (where applicable)
      Type: String
      Default: t2.small
      AllowedValues:
      - t2.small
      - t2.medium
      - m5.large
      ConstraintDescription: Must be a valid EC2 instance type
    VPC:
      Description: The VPC that the ECS cluster is deployed to
      Type: AWS::EC2::VPC::Id
    Subnet:
        Type: AWS::EC2::Subnet::Id
        Description: Subnet
  Mappings:
    AWSInstanceType2Arch:
      t2.small:
        Arch: HVMG2
      t2.medium:
        Arch: HVMG2
      m5.large:
        Arch: HVMG2
    AWSRegionArch2AMI:
      us-east-1:
        HVMG2: ami-1853ac65
      us-west-1:
        HVMG2: ami-bf5540df    
      us-west-2:
        HVMG2: ami-d874e0a0
      eu-west-1:
        HVMG2: ami-3bfab942
      eu-central-1:
        HVMG2: ami-ac442ac3
      ap-southeast-2:
        HVMG2: ami-43874721
  Resources:
    RedisCache:
      Type: AWS::EC2::Instance
      Properties:
        ImageId:
          Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - Fn::FindInMap:
            - AWSInstanceType2Arch
            - Ref: InstanceType
            - Arch
        InstanceType:
          Ref: InstanceType
        SecurityGroupIds:
        - Ref: YelbSecurityGroupRedisCache
        KeyName:
          Ref: KeyName
        Tags:
        - Key: Name
          Value: redis-cache
        SubnetId: !Ref 'Subnet'
        UserData:
          Fn::Base64:
            Fn::Join:
            - ''
            - - "#!/bin/bash -ex"
              - "\n"
              - "\n"
              - curl https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/redis-server.sh
                | bash

    YelbDb:
      Type: AWS::EC2::Instance
      Properties:
        ImageId:
          Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - Fn::FindInMap:
            - AWSInstanceType2Arch
            - Ref: InstanceType
            - Arch
        InstanceType:
          Ref: InstanceType
        SecurityGroupIds:
        - Ref: YelbSecurityGroupYelbDb
        KeyName:
          Ref: KeyName
        Tags:
        - Key: Name
          Value: yelb-db
        SubnetId: !Ref 'Subnet'
        UserData:
          Fn::Base64:
            Fn::Join:
            - ''
            - - "#!/bin/bash -ex"
              - "\n"
              - "\n"
              - curl https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/yelb-db.sh
                | bash

    YelbSecurityGroupRedisCache:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable Redis access from inside the VPC and SSH access from
          the Internet
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '6379'
          ToPort: '6379'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        VpcId: !Ref 'VPC'
    YelbSecurityGroupYelbDb:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable Postgres access from inside the VPC and SSH access
          from the Internet
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        VpcId: !Ref 'VPC'

  Outputs:

    RedisCacheEndPoint:
        Description: The private dns name of the redis server 
        Value: !GetAtt RedisCache.PrivateDnsName

    YelbDbEndPoint:
        Description: The private dns name of the yelb-db server 
        Value: !GetAtt YelbDb.PrivateDnsName